### ISSUE TITLE
FutureWarnings to be removed

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#47]
There are a bunch of future warnings with things to be changed that weren't changed yet to keep backwards compatibility.
The full list can be found with the linux command `grep "FutureWarning" $(find . -name "*.py")`.
What's the best way to remove these step by step?

**Comment by Lschoon** [comment]
I propose we leave them in until some set update. This could be `v0.5.0`, or `v0.6.0` (if we want the warnings to be included in some 'official' version, or even `v1.0.0`. Both these options are consistent with [semantic versioning](https://semver.org/), however once we go to `1.0.0+` any compatibility-changing updates need to change the major version number.

**Comment by jhauschild** [comment]
I agree. We should still include them in the official `v0.5.0` release (which I scheduled for fall this year) and then create a new branch for finalizing towards `v1.0.0` where we remove them.

**Comment by jhauschild** [comment]
See issue #70, #71, #94. I'm not sure how to handle #56 the best way, I guess we should change the behaviour of it as well before the next release.

**Comment by jhauschild** [comment]
Okay, I don't want to keep the issue open, which are basically done except for removing the code producing the deprecation warning.

Instead, let me make a list of depreciations to be removed before releasing version 1.0.0, and close the corresponding issues.

- [ ] arguments of add_multi_coupling, #56 
- [ ] deprecated access of lattice.nearest_neighbors, #64
- [ ] old scipy version without gesdd parameter for svd_robust, #70 
- [ ] combine_legs default qconj, #71
- [ ] transpose for Addition with equal labels, #94 
- [ ] old DMRG engines, DMRG parameter 'mixer' default argument.
- [ ] MPO.get_grouped_mpo
- [ ] Array.labels access
- [ ] old model files bose_hubbard[_chain].py, fermion_chain.py, fermions_hubbard
- [ ] bc_coupling argument in CouplingModel.__init__()
- [ ] prefactors argument of MPS.expectation_value_sum()
- [ ] CouplingModel.calc_H_onsite()
- [ ] deprecated chi_list, build_initial_state and setup_executable in tenpy.tools.misc

**Comment by Jakob-Unfried** [comment]
Is adressed in #389
