### ISSUE TITLE
enhance tests

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#53]
- [x] The TDVP test is very slow. Might be more efficient to compare to ED for small systems?
- [ ] include tests directly in tenpy/ folders.
- [ ] provide test "fixtures" e.g. for random arrays, and use them in other tests.
- [ ] Include tests running the basic examples in the examples/ folder
- [ ] write tests to check that the plot_* functions work. Mark them with some attribute to allow skipping them in case matplotlib is not installed.

**Comment by Jakob-Unfried** [comment]
@jhauschild:

- [x] TDVP tests have been improved by #157, I guess. They now take 9 seconds on my uncompiled version, the majority of which (7 seconds) is spent in `tdvp2_engine.run()`. I dont think we can improve runtime significiantly without comprising test coverage.
- [ ] We discussed to keep the tests in their separate directory, but we could introduce subfolders to keep them more organized. I would, however, leave them as they are for v1.0, since we will refactor the tests anyway for v2.0. do you agree?
- [ ] Same for fixtures, I would not do that for v1.0?
- [ ] There is `z_test_examples.py`, which runs the examples. 
  - [ ] We could remove the `z_` name prefix and it will be automatically run by pytest. It needs the fix in #256 to run (defining the pytest "example" mark), but then the tests do pass.
  - [ ] In #256 I have also removed the toycodes test, since they are no longer part of the main module. ok?
- [ ] I will cover the `plot_*` functions in the tests.

**Comment by Jakob-Unfried** [comment]
## Plot functions test coverage:
- [ ] dmrg plot_update_stats
- [ ] dmrg plot_sweep_stats
- [ ] lanczos plot_stats
- [ ] lattice plot_*
- [ ] terms plot_coupling_terms

**Comment by Jakob-Unfried** [comment]
All of this is either done or listed as todo in #350.
